# Site settings
title: Salman Faris
email: mail@salmanfaris.com
description: > 
  0xSalFar
baseurl: "/jekyll-test" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 0xsalfar
github_username:  salmanfarisvp

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
